/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {

  "main.baml": "generator typescript {\n  output_type \"typescript\"\n  output_dir \"../\"\n  version \"0.223.0\"\n  module_format \"esm\"\n}\n\nclass TextResponse {\n  type \"text\" @description(\"Use only when no tool is needed or all required tool results already appear in the conversation.\")\n  text string\n}\n\nclass DynamicDecision {\n  @@dynamic\n}\n\nfunction NextAction(context: string) -> DynamicDecision\n  @assert(nonempty_actions, {{ this.actions|length > 0 }}) {\n  client \"openai/gpt-4o-mini\"\n  prompt #\"\n    You are the decision layer for the Pi coding agent. Continue the supplied\n    conversation by selecting one or more independent actions from the dynamically\n    supplied tool union, or return one text response when no tool is needed. Tool\n    calls execute sequentially in listed order. Batch calls only when later calls\n    can be formed without first seeing earlier calls' output. If the user\n    asks to run, inspect, edit, or write something and no matching result is\n    present yet, you MUST select a tool. Never invent a tool result and never\n    repeat an action that already has one. Never combine a text response with tool\n    calls. Emit ordinary structured JSON, never JSON encoded inside a quoted or\n    escaped string. Do not output follow-up suggestions.\n\n    <conversation>\n    {{ context }}\n    </conversation>\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}